Repository orbit/orbit, pull requests merged in 2019-03, with the labels that each got.

#321 Don't complete exceptional tasks normally
  actors/runtime/src/main/java/cloud/orbit/actors/concurrent/WaitFreeExecutionSerializer.java
Labels: bug, semver:patch

#322 Port to ClassGraph from FastClasspathScanner
  actors/core/pom.xml
  actors/core/src/main/java/cloud/orbit/actors/runtime/ClassPathSearch.java
  actors/core/src/main/java/cloud/orbit/actors/runtime/DefaultClassDictionary.java
  actors/pom.xml
  actors/runtime/pom.xml
  actors/runtime/src/main/java/cloud/orbit/actors/runtime/FastActorClassFinder.java
Labels: misc, performance, security, semver:patch

#353 Setup Gradle plugin publishing
  build.gradle
  src/dsl/orbit-gradle-plugin/build.gradle
Labels: alpha, dsl, orbit2

#357 Fix Java sample
  samples/helloworld-java/build.gradle
Labels: alpha, orbit2
